version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      NEON_DEV_DB_URL: "${NEON_DEV_DB_URL}"
      REDIS_ADDR: "redis:6379"
      REDIS_DB: 0
      JWT_SECRET: "${JWT_SECRET}"
      CASSANDRA_HOSTS: "cassandra"
      RABBITMQ_URL: "${RABBITMQ_URL}"
    depends_on:
      - redis
      - cassandra-init
      - rabbitmq

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_SEEDS=cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES"]
      interval: 10s
      timeout: 5s
      retries: 10
  
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  worker:
    build:
      context: ../..
      dockerfile: apps/worker/Dockerfile
    container_name: litecode_worker
    restart: always
    depends_on:
      - cassandra-init
      - rabbitmq 
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
    volumes:
      - go_build_cache:/root/.cache/go-build


  cassandra-init:
    image: cassandra:latest
    depends_on:
      - cassandra
    volumes:
      - ./server/init.cql:/init.cql
    entrypoint: >
      sh -c "
      until cqlsh cassandra -e 'DESCRIBE KEYSPACES' | grep litecode; do
        echo waiting for keyspace litecode...
        sleep 5
      done;
      cqlsh cassandra -f /init.cql
      "

volumes:
  redis_data:
  go_build_cache:
  cassandra_data:
